// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dslaruypefhzegvbzqfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbGFydXlwZWZoemVndmJ6cWZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NTkyMDEsImV4cCI6MjA1ODQzNTIwMX0.BTCtgwBufNx2le_cb33WyBcobjKVvXzLWfd5V0oCi8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);